# Generated by Django 4.0.2 on 2022-02-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='addres',
            new_name='address',
        ),
    ]
